version: 1.0.1.{build}
configuration: Release

branches:
  only:
    - master

assembly_info:
  patch: true
  file: '**\*AssemblyInfo.*'
  assembly_version: 1.0.0
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

before_build:
- nuget restore

build:
  parallel: true
  verbosity: minimal

after_build:
  ps: >- 
    nuget pack $env:APPVEYOR_BUILD_FOLDER\src\JE.IdentityServer.Security.Recaptcha\JE.IdentityServer.Security.Recaptcha.csproj -IncludeReferencedProjects -OutputDirectory $env:APPVEYOR_BUILD_FOLDER\artifacts;
    nuget pack $env:APPVEYOR_BUILD_FOLDER\src\JE.IdentityServer.Security.Throttling\JE.IdentityServer.Security.Throttling.csproj -IncludeReferencedProjects -OutputDirectory $env:APPVEYOR_BUILD_FOLDER\artifacts;

skip_tags: false

artifacts:
- path: artifacts\*.nupkg
  name: Nuget

deploy:
- provider: NuGet
  api_key:
    secure: DgZLtZcCWRTg+CP/Cj8wZpBNjNWDsP2lxsEmz615tXu7UQvXyIH7WyBLXSQ/CwH6
  artifact: '**\JE*.nupkg'
  on:
    APPVEYOR_REPO_TAG: true